name: Deploy vive.works

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: ap-northeast-2
      S3_BUCKET: vive-works

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials For Devzone
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.12.0

    - name: Cache node modules
      uses: actions/cache@v2
      id: node_module_cache
      with:
        path: node_modules
        key: yarn-packages-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.node_module_cache.outputs.cache-hit != 'true'
      run: yarn
      
    - name: build
      run: yarn build
      
    - name: Build the Docker image
      run: aws s3 cp --recursive --region $AWS_REGION public s3://$S3_BUCKET

    - name: create CF Invaildation
      run: aws cloudfront create-invalidation \
        --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} \
        --paths "/*"